# Welcome to Jekyll!

# Website settings
title: "Shruti Bhargava"
description: "Shruti Bhargava"
keywords: "shruti, bhargava, shrutib, shrubh, MSR intern, Max Plank Intern"
baseurl: "/"
url: "http://shrubh.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Shruti Bhargava'
  first_name: 'Shruti'
  last_name: 'Bhargava'
  email: 'shrutib2@illinois.edu'
  facebook_username: 'shruti.bhargava.90'
  github_username: 'shrubh'
  linkedin_username: 'shruti-bhargava-90202b105'
  avatar: 'static/img/landing/Shruti.jpg'
  desc1: 'I am a final year Masters student in the Computer Science department at University of Illinois, Urbana-Champaign (UIUC), graduating in May 2019. I completed my bachelors in Computer Science and Engineering from IIT Kanpur, India in 2017. I enjoy designing algorithms and models for challenging problems in Machine Learning, Natural Language Processing and Computer Vision. Here is my [CV](https://drive.google.com/file/d/1DLswkOpaod9_JZerg-hUktbc0z26O_pZ/view?usp=sharing)'
# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
